#!/usr/bin/env python3
"""
Regenerate the master index from every <topic>/reference.json in the KB.
Machine-maintained -> no manual editing, no drift.

Writes (at KB root):
  INDEX.json   machine master list (agents read this first)
  INDEX.md     thin human mirror (optional, for browsing)

Usage: python build_index.py            # KB root = this script's ../.. dir
       python build_index.py <kb_root>
"""
import sys
import os
import json
import glob


def load_ref(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f), None
    except Exception as e:
        return None, str(e)


def main(kb_root):
    topics = []
    errors = []
    for ref_path in sorted(glob.glob(os.path.join(kb_root, "*", "reference.json"))):
        folder = os.path.basename(os.path.dirname(ref_path))
        ref, err = load_ref(ref_path)
        if err:
            errors.append({"folder": folder, "error": err})
            continue
        ent = ref.get("entities", {}) or {}
        topics.append({
            "topic_id": ref.get("topic_id", folder),
            "topic": ref.get("topic", folder),
            "folder": folder + "/",
            "reference": f"{folder}/reference.json",
            "source": f"{folder}/source.pdf",
            "pages_total": ref.get("pages_total"),
            "ingested_complete": ref.get("ingested_complete", False),
            "last_ingested": ref.get("last_ingested"),
            "keywords": ref.get("keywords", []),
            "entities": {k: v for k, v in ent.items() if v},
            "warnings_count": len(ref.get("warnings", []) or []),
        })

    index = {
        "kb_root": kb_root,
        "topic_count": len(topics),
        "usage": "Match a query against topics[].keywords / entities, then open that topic's reference.json, then read the cited pages of source.pdf. Never answer SAP questions from memory when a topic matches.",
        "topics": topics,
    }
    if errors:
        index["errors"] = errors

    with open(os.path.join(kb_root, "INDEX.json"), "w", encoding="utf-8") as f:
        json.dump(index, f, indent=2, ensure_ascii=False)

    # thin human mirror
    md = ["# SAP KB — master index (generated from reference.json files)",
          "",
          "Machine source of truth: `INDEX.json`. Do not edit this file by hand.",
          "",
          f"KB root: `{kb_root}`",
          "",
          "| Topic | Folder | Pages | Complete | Ingested | Warn |",
          "|-------|--------|-------|----------|----------|------|"]
    for t in topics:
        md.append("| {topic} | `{folder}` | {pages} | {ok} | {date} | {w} |".format(
            topic=t["topic"], folder=t["folder"], pages=t.get("pages_total", "?"),
            ok="yes" if t["ingested_complete"] else "NO",
            date=t.get("last_ingested") or "-", w=t["warnings_count"]))
    if errors:
        md += ["", "## Unreadable reference.json files", ""]
        md += [f"- `{e['folder']}`: {e['error']}" for e in errors]
    with open(os.path.join(kb_root, "INDEX.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(md) + "\n")

    print(json.dumps({"ok": True, "topics": len(topics), "errors": errors}, indent=2))


if __name__ == "__main__":
    root = sys.argv[1] if len(sys.argv) > 1 else \
        os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    main(root)
